name: uni_ocr_client
description: A universal ocr client.
version: 0.1.0
homepage: https://github.com/biyidev/uni_ocr/tree/master/packages/uni_ocr_client

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0
