name: uni_ocr
description: ''
version: 0.0.1
homepage: https://github.com/biyidev/uni_ocr

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ocr_engine_builtin:
    path: ../ocr_engine_builtin
  ocr_engine_youdao:
    path: ../ocr_engine_youdao
  uni_ocr_client: ^0.0.3

dev_dependencies:
  test: ^1.0.0
