name: uni_ocr
description:
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ocr_engine_youdao:
    path: ../ocr_engine_youdao
  uni_ocr_client: ^0.0.1

dev_dependencies:
  test: ^1.0.0
