name: uni_ocr_api
description: ''
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ocr_engine_youdao: ^0.1.0
  shelf: ^1.1.0
  shelf_router: ^1.1.2
  translation_engine_baidu: ^0.1.1
  translation_engine_caiyun: ^0.1.1
  translation_engine_deepl: ^0.1.1
  translation_engine_google: ^0.1.1
  translation_engine_iciba: ^0.1.1
  translation_engine_tencent: ^0.1.1
  translation_engine_youdao: ^0.1.1
  uni_ocr_client: ^0.1.0
  uni_translate_client: ^0.1.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner:
