name: ocr_engine_youdao
description:
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: any
  http: any
  uni_ocr_client:
    path: ../uni_ocr_client

dev_dependencies:
  test: ^1.0.0
